sansiweb/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin

admin.autodiscover()
urlpatterns = [
                url(r'^admin/', include(admin.site.urls)),
               # url(r'^$','sansiapp.views.home',name='home'),
                url(r'^asdb_input$','sansiapp.views.asdb_input',name='asdbinput'),
                url(r'^$','sansiapp.views.search',name='search'),
                url(r'^asdb_login$','sansiapp.views.asdb_login',name='asdblogin'),
                url(r'^search$','sansiapp.views.search',name='search'),
                url(r'^(?:W|w)*\d+(?:.\d+T?)*$','sansiapp.views.search_result',name='search_result')
              ]

sansiapp/models.py
#-*- coding:utf-8 -*-
from django.db import models

# 售后登录账号表
class AfterSalesLogin(models.Model):
    asl_name=models.CharField(max_length=10)
    asl_passwd=models.CharField(max_length=20)

    def __unicode__(self):
        return self.asl_name

# 售后单表 
class AfterSales(models.Model):
    SERVICE_TYPE = (('weixiu','维修'),('zhenggai','整改'),('tuihuo','退货'))
    FLAG_TYPE = (('finished','结束'),('unfinished','未完成'))
    as_date=models.DateField()#日期
    as_number=models.CharField(max_length=20)#单号
    as_type=models.CharField(max_length=10,choices=SERVICE_TYPE)#售后类型
    as_flagtype=models.CharField(max_length=10,choices=FLAG_TYPE)#是否完成标识
    as_name=models.CharField(max_length=20)#业务员姓名
    as_client=models.CharField(max_length=60,blank=True,null=True)#客户公司名称
    as_clientname=models.CharField(max_length=40,blank=True,null=True)#客户姓名
    as_clientphone=models.CharField(max_length=40,blank=True,null=True)#客户电话
    as_clientaddress=models.CharField(max_length=100,blank=True,null=True)#客户地址
    as_cranetype=models.CharField(max_length=20,blank=True,null=True)#起重机类型
    as_metertype=models.CharField(max_length=20,blank=True,null=True)#仪表类型
    as_cranemodel=models.CharField(max_length=20,blank=True,null=True)#起重机型号规格
    as_metermodel=models.CharField(max_length=20,blank=True,null=True)#仪表型号
    as_faultdescribe=models.TextField(max_length=200,blank=True,null=True)#故障描述
    as_faultanalyze=models.TextField(max_length=200,blank=True,null=True)#故障分析
    as_faultresult=models.TextField(max_length=200,blank=True,null=True)#处理结果

    def __unicode__(self):
        return self.as_number

# 存储临时表单
class FormTemp(models.Model):
    TYPE_CHOICES = (('kong',' '),('zhenggai','整改'),('weixiu','维修'),('tuihuo','退货'))
    TYPE_FLAG = (('kong',''),('finished','结束'),('unfinished','未完成'))

    searchDateStart = models.DateField(blank=True,null=True)
    searchDateEnd = models.DateField(blank=True,null=True)
    searchNumber = models.CharField(max_length=20,blank=True,null=True)
    searchClient= models.CharField(max_length=60,blank=True,null=True)
    searchClientName = models.CharField(max_length=40,blank=True,null=True)
    searchName = models.CharField(max_length=20,blank=True,null=True)
    searchKeyWord = models.CharField(max_length=40,blank=True,null=True)    
    searchType = models.CharField(max_length=10,choices=TYPE_CHOICES,blank=True,null=True)    
    searchFlag = models.CharField(max_length=10,choices=TYPE_FLAG,blank=True,null=True)    

sansiapp/forms.py
#-*- coding:utf-8 -*-
#by msw 20170714

from django import forms
from django.forms import ModelForm
from sansiapp.models import AfterSales

TYPE_CHOICES = (('kong',' '),('zhenggai','整改'),('weixiu','维修'),('tuihuo','退货'))
TYPE_FLAG = (('kong',''),('finished','结束'),('unfinished','未完成'))

# 售后录入登录
class formAfterSalesLogin(forms.Form):
    name = forms.CharField(label='账号',max_length=20)
    passwd = forms.CharField(label='密码',max_length=20,widget=forms.PasswordInput())

# 售后申请单模板
class formAfterSalesRequest(ModelForm):
    class Meta:
        model=AfterSales
        fields=['as_date','as_number','as_type','as_flagtype','as_name','as_client','as_clientname','as_clientphone','as_clientaddress','as_cranetype','as_cranemodel','as_metermodel','as_faultdescribe','as_faultanalyze','as_faultresult']

# 查询
class formSearch(forms.Form):
    searchDateStart = forms.DateField(label='开始日期',required=False)
    searchDateEnd = forms.DateField(label='结束日期',required=False)
    searchNumber = forms.CharField(label='生产单号',required=False,max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
    searchClient= forms.CharField(label='客户名称',required=False,max_length=40,widget=forms.TextInput(attrs={'class':'textinput_special'}))
    searchClientName = forms.CharField(label='联系人',required=False,max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
    searchName = forms.CharField(label='销售员姓名',required=False,max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
    searchKeyWord = forms.CharField(label='关键字查询',required=False,max_length=40,widget=forms.TextInput(attrs={'class':'textinput_special'}))    
    searchType = forms.ChoiceField(label='售后类型',required=False,widget=forms.Select(attrs={'class':'select_special'}),choices=TYPE_CHOICES)    
    searchFlag = forms.ChoiceField(label='结束标志',required=False,widget=forms.Select(attrs={'class':'select_special'}),choices=TYPE_FLAG)    

## 售后申请单模板
#class formAfterSaleRequest(forms.Form):
#    service_type = (('weixiu','维修'),('zhenggai','整改'))
#
#    after_sale = forms.ChoiceField(choices=service_type)#售后类型
#
#    number = forms.CharField(label='售后单号',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#    formdate = forms.DateField(label='日期')
#
#    clientname = forms.CharField(label='客户名称',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#    name = forms.CharField(label='联系人',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#
#    clientaddress = forms.CharField(label='客户地址',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#    phone = forms.CharField(label='联系电话',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#
#    cranetype = forms.CharField(label='起重机类型',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))   #    metertype = forms.CharField(label='仪表类型',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#
#    cranemodel = forms.CharField(label='起重机型号',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#    metermodel = forms.CharField(label='仪表型号',max_length=20,widget=forms.TextInput(attrs={'class':'textinput_special'}))
#
#    faultdescribe = forms.CharField(label='故障描述',widget=forms.Textarea(attrs={'cols':'58'}))
#    faultanalyze = forms.CharField(label='故障分析',widget=forms.Textarea(attrs={'cols':'58'}))
#    faultresult = forms.CharField(label='处理结果',widget=forms.Textarea(attrs={'cols':'58'}))

## 销售需填写的客户信息和故障描述
#class formAfterSaleInfo(forms.Form):
#    service_type = (('weixiu','维修'),('zhenggai','整改'))
#
#    saler = forms.CharField(label='下单人',max_length=10)
#    after_sale = forms.ChoiceField(choices=service_type)
#
#    number = forms.CharField(label='生产单号',max_length=20)
#    formdate = forms.DateField(label='日期')
#
#    clientname = forms.CharField(label='客户名称',max_length=20)
#    name = forms.CharField(label='联系人',max_length=20)
#
#    clientaddress = forms.CharField(label='客户地址',max_length=20)
#    phone = forms.CharField(label='联系电话',max_length=20)
#
#    cranetype = forms.CharField(label='起重机类型',max_length=20)   
#    metertype = forms.CharField(label='仪表类型',max_length=20)
#
#    cranemodel = forms.CharField(label='起重机型号',max_length=20)
#    metermodel = forms.CharField(label='仪表型号',max_length=20)
#
#    faultdescribe = forms.CharField(label='故障描述',widget=forms.Textarea)
#
## 售后相关人员填写，故障分析和处理结果
#class formAfterSaleResult(forms.Form):
#    faultanalyze = forms.CharField(label='故障分析',widget=forms.Textarea)
#    faultresult = forms.CharField(label='处理结果',widget=forms.Textarea)

sansiapp/views.py
#!/usr/bin/python
#-*- coding:utf-8 -*-
#mingshwiu 20170714
# 2017年11月4日，增加结束标志查询
# git test

import time
import re
from django.shortcuts import render,render_to_response
from django.http import HttpResponse
from sansiapp.models import AfterSales,AfterSalesLogin
from .forms import formAfterSalesRequest,formAfterSalesLogin,formSearch,TYPE_CHOICES,TYPE_FLAG

def home(req):
    form = formAfterSalesRequest()
    return render(req,'home.html',{'form':form})

def asdb_login(req):
    if req.method == 'POST':
        form = formAfterSalesLogin(req.POST)
        if form.is_valid():
            objform = form.cleaned_data
            if AfterSalesLogin.objects.filter(asl_name=objform['name']):
                if AfterSalesLogin.objects.filter(asl_passwd=objform['passwd']):
                    form_input = formAfterSalesRequest(initial={'as_date':'格式：2017-01-01','as_faultdescribe':'字数限制100字','as_faultanalyze':'字数限制100字','as_faultresult':'字数限制100字'})
                    return render(req,'home.html',{'form':form_input }) 
                return render(req,'base_login.html',{'form':form,'error_info':'密码错误！'})
            return render(req,'base_login.html',{'form':form,'error_info':'用户名错误！'})
        else:
            return render(req,'base_login.html',{'form':form,'error_info':form.errors})
    else:
        form = formAfterSalesLogin()
    return render(req,'base_login.html',{'form':form})

def asdb_input(req):
    if req.method == 'POST':
        form = formAfterSalesRequest(req.POST)
        if form.is_valid():
#            info = form.save()
#            info.save()
            form.save()
            return render(req,'home.html',{'form':form,'result_info':'数据保存成功!'})
        else:
            return render(req,'home.html',{'form':form,'error_info':form.errors})
    else:
        form = formAfterSalesRequest(initial={'as_date':'例：2017-01-01','as_faultdescribe':'字数限制100字','as_faultanalyze':'字数限制100字','as_faultresult':'字数限制100字'})
    return render(req,'home.html',{'form':form})

def check_bit_flag(objdb):
    if objdb:
        return True   #按条件搜索到结果
    else:
        return False  #按条件没有搜索到结果

def search(req):

    bitFlag=True

    if req.method == 'GET':
        form = formSearch(req.GET)
        if form.is_valid():
            objforms=form.cleaned_data

            # 日期判断、查询
            if objforms['searchDateStart'] is not None:
                if objforms['searchDateEnd'] is not None:
                    OBJDB = AfterSales.objects.filter(as_date__range=(objforms['searchDateStart'],objforms['searchDateEnd']))
                    bitFlag=check_bit_flag(OBJDB)
                else:
                    # 只填入开始日期
                    OBJDB=AfterSales.objects.filter(as_date=objforms['searchDateStart'])
                    bitFlag=check_bit_flag(OBJDB)
            elif objforms['searchDateEnd'] is not None:
                # 只填入结束日期
                OBJDB = AfterSales.objects.filter(as_date=objforms['searchDateEnd'])
                bitFlag=check_bit_flag(OBJDB)
            else:
                OBJDB=[]
             
            # 生产单号查询
            if objforms['searchNumber'] != '':
                # 判断单号是不是纯数字
                if re.match(r'^\d+$',objforms['searchNumber']) is not None:
                    if OBJDB and bitFlag:
                        OBJDB = OBJDB.filter(as_number__contains = objforms['searchNumber'])
                        bitFlag = check_bit_flag(OBJDB)
                    elif (not OBJDB) and bitFlag:
                        OBJDB = AfterSales.objects.filter(as_number__contains = objforms['searchNumber'])
                        bitFlag = check_bit_flag(OBJDB)
                else:
                    if OBJDB and bitFlag:
                        OBJDB = OBJDB.filter(as_number=objforms['searchNumber'])
                        bitFlag = check_bit_flag(OBJDB)
                    elif (not OBJDB) and bitFlag:
                        OBJDB = AfterSales.objects.filter(as_number=objforms['searchNumber'])
                        bitFlag = check_bit_flag(OBJDB)

            # 客户名称查询
            if objforms['searchClient'] != '':
                if OBJDB and bitFlag:
                    OBJDB = OBJDB.filter(as_client__contains=objforms['searchClient'])
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    OBJDB = AfterSales.objects.filter(as_client__contains=objforms['searchClient'])
                    bitFlag = check_bit_flag(OBJDB)

            # 联系人查询
            if objforms['searchClientName'] != '':
                if OBJDB and bitFlag :
                    OBJDB = OBJDB.filter(as_clientname=objforms['searchClientName'])
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    OBJDB = AfterSales.objects.filter(as_clientname=objforms['searchClientName'])
                    bitFlag = check_bit_flag(OBJDB)

            # 销售员查询
            if objforms['searchName'] != '':
                if OBJDB and bitFlag :
                    OBJDB = OBJDB.filter(as_name=objforms['searchName'])
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    OBJDB = AfterSales.objects.filter(as_name=objforms['searchName'])
                    bitFlag = check_bit_flag(OBJDB)

            # 关键字查询
            if objforms['searchKeyWord'] != '':
                if OBJDB and bitFlag :
                    OBJDB = OBJDB.filter(as_faultanalyze__contains=objforms['searchKeyWord'])
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    OBJDB = AfterSales.objects.filter(as_faultanalyze__contains=objforms['searchKeyWord'])
                    bitFlag = check_bit_flag(OBJDB)

            # 售后类型查询
            if objforms['searchType'] != 'kong' and objforms['searchType'] != '':
                if OBJDB and bitFlag:
                    for n in range(len(TYPE_CHOICES)):
                        if objforms['searchType'] in TYPE_CHOICES[n]:
                            temp=TYPE_CHOICES[n][1]
                            break
                    OBJDB = OBJDB.filter(as_type=temp)
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    for n in range(len(TYPE_CHOICES)):
                        if objforms['searchType'] in TYPE_CHOICES[n]:
                            temp=TYPE_CHOICES[n][1]
                            break
                    OBJDB = AfterSales.objects.filter(as_type=temp)
                    bitFlag = check_bit_flag(OBJDB)

            # 结束标志查询
            if objforms['searchFlag'] != 'kong' and objforms['searchType'] != '':
                if OBJDB and bitFlag:
                    for n in range(len(TYPE_FLAG)):
                        if objforms['searchFlag'] in TYPE_FLAG[n]:
                            temp=TYPE_FLAG[n][1]
                            break
                    OBJDB = OBJDB.filter(as_flagtype=temp)
                    bitFlag = check_bit_flag(OBJDB)
                elif (not OBJDB) and bitFlag:
                    for n in range(len(TYPE_FLAG)):
                        if objforms['searchFlag'] in TYPE_FLAG[n]:
                            temp=TYPE_FLAG[n][1]
                            break
                    OBJDB = AfterSales.objects.filter(as_flagtype=temp)
                    bitFlag = check_bit_flag(OBJDB)


            if OBJDB :
                num = len(OBJDB)
            else:
                OBJDB = AfterSales.objects.filter(id=1)
                num = len(OBJDB) - 1

            req.session['FORM'] = form
            req.session['OBJDB'] = OBJDB
            req.session['NUM'] = num
            #print OBJDB
            #print len(OBJDB)
            return render(req,'base_query.html',{'form':form,'objdbs':OBJDB,'num':num,'item_objdb':OBJDB})
        else:
            return render(req,'base_query.html',{'form':form,'error_info':form.errors})

def search_result(req):
    GLOBAL_FORM=req.session['FORM']
    GLOBAL_OBJDB=req.session['OBJDB']
    GLOBAL_NUM=req.session['NUM']
#    print "into search_resutl"
#    print req.get_full_path()
#    print
#    print req.path
    item = GLOBAL_OBJDB.filter(as_number=req.path[1:])
    return render_to_response('base_query.html',{'form':GLOBAL_FORM,'objdbs':GLOBAL_OBJDB,'num':GLOBAL_NUM,'item_objdb':item})
#
#def is_valid_date(str):
#    '''判断所给字符串是否为有效日期格式'''
#    try:
#        time.strptime(str, "%Y-%m-%d")
#        return True
#    except:
#        return False
#

sansiapp/templates/base.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html";charset="utf-8">
   <title>{% block title %}默认标题{% endblock %}</title>
   <style>
       #para_td {text-align:center}
   </style>
</head>
<body>
   	<table width=100% align="center">
	<tr>
	   {% block manually %}<td align="right"><a href="/login.html" target="_blank">管理入口</a></td>{% endblock %}
	</tr>
	<tr>
	  <td align="center"> <font face="Verdana" color=#0000ff size=5><b>生产任务单查询</b></font></td>
	</tr>
    <tr>
       <td align="center"> 
          <form name="search" action="/search_pronumber" method="get">
           {% if date_flag %}
                日期: <input type="text" size=20 name="pro_date" value="2000-02-01">
           {% else %}
                日期: <input type="text" size=20 name="pro_date" value="日期格式不正确，例：2000-02-01,2000-03-01">
           {% endif %}

           单号:<input type="text" size=20 name="pro_number">
               
           姓名:<input type="text" size=20 name="pro_name">
               
           客户:<input type="text" size=20 name="pro_clientname">
           
           起重机类型:<input type="text" size=20 name="pro_cranetype">
           <input name="submit" type=submit value="查询">
           </form>	   
           {% include "result.html" %}
		</td>
	 </tr>	
     </table>
	
</body>
</html>

sansiapp/templates/base_query.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html";charset="utf-8">
<title>{% block title %}默认标题{% endblock %}</title>
<style>
#id_searchDateStart
{
    width:100px;
}

#id_searchDateEnd
{
    width:100px;
}

#id_searchClientName
{
    width:100px;
}

#id_searchName
{
    width:100px;
}

#id_searchClient
{
	width:100px;
}

#id_searchNumber
{
	width:100px;
}


#td_result_list 
{
    text-align:center;
    background-color:#f29c16;
}

#td_as_detail 
{
	 width:15%;
    text-align:center;
    background-color:#f29c16;
}

#td_result_vaule
{
    width:15%;    
    text-align:center;
    background-color:#bcf216;
}

#td_result_vaule_fault
{
    text-align:left;
    background-color:#bcf216;
}

#td_hr_width /*设表格宽*/
{
	width:2px;
}

table
{
    text-align:center;
}

th
{
	background-color:#b09c52;
    text-align:center;
	margin:0px;
	border:1px;
	padding:3x 0px 3px;
}

#td_info
{
	color:#ff0000;
	text-align:center;
}

#hr_vertical /*垂直分割线*/
{
	width:2px;
	height:20px;
}

.textinput_special
{
	margin:0px 2px 0px;
	border:0px;
	padding:0px;
	width:205px;
	height:22px;
	line-height:22px;
}

.select_special
{
	margin:0px;
	border:0px;
	padding:0px;
	height:22px;
}

</style>
</head>
<body style="background-color:#b0e468">
   <table width=100% align="center">
	<tr>
	   {% block manage %}<td align="right"><a href="/asdb_login" target="_blank">管理入口</a></td>{% endblock %}
	</tr>
	<tr>
	  <td align="center"> <font face="Verdana" color=#0000ff size=5><b>售后记录查询</b></font></td>
	</tr>
	</table>
	<table width=100% align="center">
	<tr>
        {% block errinfo %}<td id="td_info"><p>{{ error_info }}</td>{% endblock %}
	</tr>
	<tr>
        {% block resultinfo %}<td id="td_info"><p>{{ result_info }}</td>{% endblock %}
	</tr>
	</table>

  <table width=100% align="center"> 
     <tr>
     <td align="center">
  	    <form name="search" action="/search" method="get">
		  <table align="center">
		  <tr>
		  <td style="width:300px;text-align:left"><label>查询时间段</label>{{form.searchDateStart}}-{{form.searchDateEnd}}</td>
          <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
		  <td ><label>生产单号</label>{{form.searchNumber}}</td>
		  <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
		  <td ><label>客户名称</label> {{form.searchClient}}</td>
		  <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
		  <td ><label>联系人</label> {{form.searchClientName}}</td>
		  <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
		  <td ><label>销售员姓名</label> {{form.searchName}}</td>
		  <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
		  <td style="text-align:left"><input name="submit" type=submit value="查询"></td>       
		  </tr>
          <tr>
	        <td style="text-align:left;height:22px;width:300px"><label>关键字查询</label>{{form.searchKeyWord}}</td>
			 <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
			 <td style="text-align:left;height:22px;"><label>售后类型</label>{{form.searchType}}</td>
			 <td id="td_hr_width"><hr id="hr_vertical"></hr></td>
			 <td style="text-align:left;height:22px;"><label>结束标志</label>{{form.searchFlag}}</td>
          </tr>
		  </table>
		</form>
	 </td>
	 </tr>
 </table>
 <table width=100%>
    <tr>
       <td><hr style="width:100%;height:2px;"></td>
    </tr>
  </table>
 <table style="width:100%;text-align:center;">
 <tr style="width:100%;">
	<th colspan="2"><font face="Verdana" color=#0000ff size=5><b>查  询  结  果</b></font></th> 
 </tr>
 <tr>
     <td style="width:60%;vertical-align:top;text-align:right;">
        <table align="center" style="width:100%">	
         <tr>
            <th >序号</th>
            <th >日期</th>
            <th >生产单号</th>
            <th>客户姓名</th>
            <th>联系人</th>
            <th>销售员姓名</th>
            <th>是否结束</th>
         </tr>
	      {% for item in objdbs %}
	      <tr>
		      <td id="td_result_list">{{item.id}}</td>
		      <td id="td_result_list">{{item.as_date|date:"Y-m-d"}}</td>
              <td id="td_result_list"><a href={{item.as_number}}>{{item.as_number}}</a></td>
			  <td id="td_result_list">{{item.as_client}}</td>  
			  <td id="td_result_list">{{item.as_clientname}}</td>          
              <td id="td_result_list">{{item.as_name}}</td>
              <td id="td_result_list">{{item.as_flagtype}}</td>
         </tr>
	      {% endfor %}
	      <tr>
	         <td id="td_result_list"></td>
	         <td id="td_result_list"></td>
             <td id="td_result_list">结果共有：</td>
             <td id="td_result_list">{{num}}</td>
             <td id="td_result_list">条</td>
             <td id="td_result_list"></td>
             <td id="td_result_list"></td>
         </tr>
	      </table>
	   </td>
 
      <td style="width:40%;vertical-align:top;text-align:left">
         <table style="width:100%">
         <tr>
            <th colspan="4">售后单明细</th>
         </tr>
            {% for item in item_objdb %}
                <table style="width:100%">
                    <tr>
                       <td id="td_as_detail">日期:</td><td id="td_result_vaule">{{ item.as_date|date:"Y-m-d"}}</td>
                    <td id="td_as_detail">生产单号:</td><td id="td_result_vaule">{{ item.as_number}}</td>
                    </tr>					
                    <tr>
                       <td id="td_as_detail">售后类型:</td><td id="td_result_vaule">{{item.get_as_type_display }}</td>
                       <td id="td_as_detail">销售员姓名:</td><td id="td_result_vaule">{{item.as_name}}</td>
                    </tr>
                    <tr>
                       <td id="td_as_detail">客户名称:</td><td id="td_result_vaule">{{item.as_client }}</td>
                    <td id="td_as_detail">联系人:</td><td id="td_result_vaule">{{item.as_clientname }}</td>
                    </tr>
                    <tr>
                       <td id="td_as_detail">客户地址:</td><td id="td_result_vaule">{{item.as_clientaddress }}</td>
                       <td id="td_as_detail">联系电话:</td><td id="td_result_vaule">{{item.as_clientphone }}</td>
                    </tr>
                    <tr>
                       <td id="td_as_detail">起重机类型:</td><td id="td_result_vaule">{{item.as_cranetype }}</td>
                    <td id="td_as_detail">起重机型号:</td><td id="td_result_vaule">{{item.as_cranemodel }}</td>
                    </tr>
                    <tr><td id="td_as_detail">仪表型号/编号:</td><td id="td_result_vaule">{{item.as_metertype }}</td></tr>
                    
                    <tr><td id="td_as_detail">故障描述：</td><td id="td_result_vaule_fault" colspan="3">{{ item.as_faultdescribe}}</td></tr>
                    <tr><td id="td_as_detail">故障分析：</td><td id="td_result_vaule_fault" colspan="3">{{ item.as_faultanalyze}}</td></tr>
                    <tr><td id="td_as_detail">处理结果：</td><td id="td_result_vaule_fault" colspan="3">{{ item.as_faultresult}}</td></tr>
                    <tr>
                        <td colspan="4"><hr style="width:100%;height:2px;"></td>
                    </tr>
                </table>
           {% endfor %}
         </table>
       </td>                
 </tr>		 
</table>	 
	
</body>
</html>

sansiapp/templates/home.html
{% extends 'base2.html' %}
{% block title %}售后单录入{% endblock %}

sansiapp/templates/manually.html
<td align="right"><a href="/manually.html" target="_blank">手动录入</a></td>

sansiapp/templates/search.html
{% extends 'base.html' %}
{% block title %}生产任务单查询{% endblock %}
{% block manually %}
{% include 'manually.html' %}
{% endblock %}